### ISSUE TITLE
using /time 0 causes massive time acceleration

### ISSUE THREAD

**Issue by sofar** [MinetestForFun/time_regulation#4]
this mod currently modifies the server value of time_speed in minetest.conf, but then uses it and calculates a new value for it. Manually adjusting time causes it to go nuts.

I suspect that the actual value of time_speed in minetest.conf should never be _changed_. It should just be used in the calculations.

**Comment by sofar** [comment]
I also think there's a calculation bug here:

```
2016-05-12 14:19:36: ACTION[Server]: [TimeRegulation] Applied time speeds:
2016-05-12 14:19:36: ACTION[Server]: [TimeRegulation]   Day: 135.02016611407
2016-05-12 14:19:36: ACTION[Server]: [TimeRegulation]   Night: 154.25938329989
```

it seems that the values here need to be divided by 2. The time_speed was set to 72, and the above values indicate that it's displaying +/- 144.

**Comment by sofar** [comment]
Actually, I don't even need to do anything. After a while it goes nuts all by itself.

**Comment by Lymkwi** [comment]
> I suspect that the actual value of time_speed in minetest.conf should never be changed. It should just be used in the calculations.

I have never heard/seen minetest change variables from a configuration file, unless you are using minetestserver without providing a specific configuration file, in which case it might write the new value (minetest behaves in weird fashions)
I could add a shutdown hook to set time_speed to the original value, but I also think the problem here comes from that value changing in the code, and being reloaded. Since Minetest stores the new value of time_speed, each time I try to reload it (for reasons of taking any new value in account), the calculations are based upon faster and faster periods of time. I think it's a problem of retrieving the value multiple times, which isn't useful anymore. I'll investigate further.
(Also, if you do the maths :

```
-- For those formulas we use the human time h and the time speed t :
h = 1440 / t
t = 1440 / h
t * h = 1440
-- We have 1440 minutes in one day, and time_speed = 1 makes a game day equal in length to a real day

-- So we calculate like this :
1440 / 72 = 20 -- Human minutes corresponding to time_speed = 72
1440 / 135 = ~10.66667 mins (~50% of a 20 minutes day/night cycle)
1440 / 154 = ~9.3506 mins (~50% of a 20 minutes day/night cycle)
-- It works
```

)

**Comment by Lymkwi** [comment]
This should fix your problem : https://github.com/minetest-mods/time_regulation/commit/e9787b55aa4b9e4a293da24103c322f897d65164
I also diminished the interval between two calls of the loop.

**Comment by sofar** [comment]
This still does the wrong thing:
- edit minetest.conf, set `time_speed = 72` (default)
- start minetest with `seasonal_time_regulation = true`
- start world with this mod enabled
- stop minetest withing 5 seconds.
- read `time_speed` value from minetest.conf

expected value: somewhere near `72`
actual value: `143.076`

**Comment by Lymkwi** [comment]
> actual value: 143.076

Okay, then minetest is dumb enough to not overwrite config files given in the command line but does it for the others, and I'm suppoed to adapt the code to both behaviors...
I'll add a shutdown hook to reset time_speed to the correct value; since I since to mess with it to accelerate time it's normal that the value corresponds to the one currently in place at shutdown, but I wasn't expecting MT to overwrite it in the config file...
The fix will be here soon.

EDIT: I tested with both stable and dev... Both do not override even when I do not provide a config file in the command line. Anyway, here's the fix, could you check whether of not you can reproduce your issue with it please? https://github.com/minetest-mods/time_regulation/commit/5faec7598fd1d493467ccdd79086b7360c559606

**Comment by sofar** [comment]
better, it doesn't go nuts yet :)

```
2016-05-16 17:49:45: ACTION[Server]: [TimeRegulation] Applied time speeds:
2016-05-16 17:49:45: ACTION[Server]: [TimeRegulation]   Day: 101.13989852951
2016-05-16 17:49:45: ACTION[Server]: [TimeRegulation]   Night: 249.9004135773
```

what I don't get is why these are not centered around 72. I thin there is still a factor 2 off here, and days/nights are going over very quickly.

**Comment by Lymkwi** [comment]
> what I don't get is why these are not centered around 72.

I recalcuated and you seem to be right about human times. Since we use half the time the game would take to do a night/day cycle (either day, or either night), there is a factor 2 off in the calculation.
I'll fix that as soon as possible.

**Comment by Lymkwi** [comment]
Here's the commit, I hadn't commented about it.
https://github.com/minetest-mods/time_regulation/commit/e356df76161a9a1727c57cf38dd88b4cf684eae0

**Comment by sofar** [comment]
Excellent. As far as I have seen in quick testing everything looks OK.

I'm closing this now with the following notes:
- logging is _really_ verbose. In the future this should print out way less messages I think, to prevent log spam.
- if I spot bugs I'll open new issues ;)

**Comment by Lymkwi** [comment]
> if I spot bugs I'll open new issues ;)

Thanks for the feedbacks (however negative/positive they are), as always!
